[config]
skip_core_tasks = true
default_to_workspace = false

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["contracts/room-contract", "ui"]
CONTRACT_TARGET = "wasm32-unknown-unknown"
CONTRACT_NAME = "room_contract"

[tasks.clean]
description = "Clean build artifacts"
command = "cargo"
args = ["clean"]

[tasks.build-contract]
description = "Build the room contract WASM"
command = "cargo"
args = ["build", "--release", "--target", "${CONTRACT_TARGET}", "-p", "room-contract", "--target-dir", "target"]


[tasks.build-ui]
description = "Build the Dioxus UI"
dependencies = ["build-contract"]
command = "dx"
args = ["build"]
cwd = "./ui"

[tasks.build]
description = "Build everything"
dependencies = ["build-ui"]

[tasks.dev]
description = "Development build"
dependencies = ["copy-contract"]
command = "dx"
args = ["serve"]
cwd = "./ui"
