[config]
skip_core_tasks = true
default_to_workspace = false

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = ["contracts/room-contract", "ui"]
CONTRACT_TARGET = "wasm32-unknown-unknown"
CONTRACT_NAME = "room_contract"

[tasks.clean]
description = "Clean build artifacts"
command = "cargo"
args = ["clean"]

[tasks.build-contract]
description = "Build the room contract WASM"
condition = { env_set = ["FORCE_CONTRACT_BUILD"], env_true = ["FORCE_CONTRACT_BUILD"] }
command = "cargo"
args = ["build", "--release", "--target", "${CONTRACT_TARGET}", "-p", "room-contract", "--target-dir", "target"]

[tasks.build-contract-if-needed]
description = "Build the room contract WASM if needed"
run_task = [
    { name = "build-contract" }
]
condition_script = [
    """
    if [ ! -f "target/wasm32-unknown-unknown/release/${CONTRACT_NAME}.wasm" ]; then
        exit 0
    fi
    if [ -n "$(find contracts/room-contract/src -type f -newer target/wasm32-unknown-unknown/release/${CONTRACT_NAME}.wasm)" ]; then
        exit 0  
    fi
    exit 1
    """
]

[tasks.build-ui]
description = "Build the Dioxus UI"
dependencies = ["build-contract-if-needed"]
command = "dx"
args = ["build"]
cwd = "./ui"

[tasks.build]
description = "Build everything"
dependencies = ["build-ui"]

[tasks.dev]
description = "Development build"
dependencies = ["copy-contract"]
command = "dx"
args = ["serve"]
cwd = "./ui"
