[package]
name = "room-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
ciborium.workspace = true
getrandom.workspace = true
freenet-scaffold = { path = "../../scaffold" }
freenet-stdlib = { path = "../../stdlib/rust", features = ["contract"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
strip = true

