[package]
name = "room-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
serde.workspace = true
ciborium.workspace = true
itertools.workspace = true
getrandom = { workspace = true, features = ["js"] }
freenet-scaffold = { path = "../../scaffold" }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'
strip = true

# Internal dependencies
freenet-stdlib = { path = "../../stdlib/rust", features = ["net"] }
