[package]
name = "keygen"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
ed25519-dalek = "2"
toml = "0.8"
dirs = "6.0.0"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }
