[package]
name = "web-container-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
river-common.workspace = true
ed25519-dalek = { workspace = true, features = ["rand_core"] }
toml = "0.8"
dirs = "6.0.0"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }
ciborium.workspace = true
