[alias]
test = "test --target=x86_64-unknown-linux-gnu"

[build]
# Default target for normal builds is wasm
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
# Don't run tests for wasm target
runner = false

[profile]

[profile.dioxus-wasm]
inherits = "dev"
opt-level = 2

[profile.dioxus-server]
inherits = "dev"
opt-level = 2

[profile.dioxus-android]
inherits = "dev"
opt-level = 2
