//! In-room direct-message UI (#243 Phase 2, #258 follow-ups).
//!
//! UX model: clicking a member opens the member-info modal, which has a
//! "Send Direct Message" button. That button opens this module's
//! [`DmThreadModal`]: a per-pair thread of decrypted DMs plus a composer.
//!
//! A second, primary entry point lives in the **left rail under Rooms**:
//! [`crate::components::room_list::dm_rail_section::DmRailSection`] lists
//! every open DM thread across ALL rooms the local user is in, with an
//! unread badge per thread. Clicking a row opens [`DmThreadModal`] for
//! that (room, peer). Replaces the earlier per-room inbox button in the
//! members panel (zorolin feedback, 2026-05-16).
//!
//! Persistence model: all message state lives in `ChatRoomStateV1`. This
//! module only adds *view* state — currently open thread, last-seen
//! timestamps per peer for unread tracking. Last-seen state is purely
//! in-memory; reloading the page seeds it from the room state (see
//! [`seed_dm_last_seen_if_needed`]) so previously-read DMs don't pop
//! back as unread on every page load.

mod dm_thread_modal;
mod invite_via_dm_picker_modal;

pub use dm_thread_modal::DmThreadModal;
pub use invite_via_dm_picker_modal::InviteViaDmPickerModal;

use dioxus::prelude::*;
use ed25519_dalek::VerifyingKey;
use river_core::chat_delegate::{HiddenDmThreadEntry, OutboundDmEntry};
use river_core::room_state::direct_messages::PurgeToken;
use river_core::room_state::member::MemberId;
use std::collections::HashMap;

/// Currently-open DM thread, addressed by (room_owner_vk, counterparty).
/// `None` means no DM modal is open.
pub static OPEN_DM_THREAD: GlobalSignal<Option<(VerifyingKey, MemberId)>> = Global::new(|| None);

/// Per-(room, peer) timestamp (unix seconds) of the most recent DM the local
/// user has actually viewed in [`DmThreadModal`]. Anything in
/// `room.direct_messages.messages` addressed to the local user with
/// `timestamp > last_seen` counts as unread.
pub static DM_LAST_SEEN: GlobalSignal<HashMap<(VerifyingKey, MemberId), u64>> =
    Global::new(HashMap::new);

/// Mark every DM from `peer` in `room` as seen up to (and including) the
/// most recent inbound message timestamp known to the synchronizer.
pub fn mark_thread_read(room: VerifyingKey, peer: MemberId, up_to_ts: u64) {
    crate::util::defer(move || {
        DM_LAST_SEEN.with_mut(|seen| {
            let entry = seen.entry((room, peer)).or_insert(0);
            if up_to_ts > *entry {
                *entry = up_to_ts;
            }
        });
    });
}

/// Open the DM thread modal for `(room, peer)`. Closes any other open
/// thread first.
pub fn open_dm_thread(room: VerifyingKey, peer: MemberId) {
    crate::util::defer(move || {
        *OPEN_DM_THREAD.write() = Some((room, peer));
    });
}

/// "Share an invite via DM…" picker state. When `Some((room, peer))`, the
/// [`InviteViaDmPickerModal`] is visible and offers to generate an invite
/// for ANOTHER room and pre-fill a DM to `peer` in `room` with the invite
/// URL. See issue #252.
pub static INVITE_VIA_DM_PICKER: GlobalSignal<Option<(VerifyingKey, MemberId)>> =
    Global::new(|| None);

/// Currently in-flight pick generated by [`InviteViaDmPickerModal`]'s row
/// click. Lives at module scope (not `use_signal` inside the picker)
/// because a watchdog task can outlive the picker's unmount on the
/// success path; reading a use_signal whose owning component has been
/// dropped panics in Dioxus. The `generation` field lets stale
/// watchdogs short-circuit immediately when a newer pick has taken over
/// (Codex P2 + Skeptical M1/L3 on PR #260).
#[derive(Clone, Copy, PartialEq, Debug)]
pub struct InvitePickInflight {
    /// Monotonic counter — every fresh row-click bumps this. Watchdogs
    /// capture it at scheduling time and no-op if it has moved on.
    pub generation: u64,
    /// Which candidate room the user picked, for the row spinner.
    pub room_vk: VerifyingKey,
}

pub static INVITE_VIA_DM_PICKER_INFLIGHT: GlobalSignal<Option<InvitePickInflight>> =
    Global::new(|| None);

/// Body to pre-fill into the DM composer the next time
/// [`DmThreadModal`] renders for the matching (room, peer). Used by the
/// "Share an invite via DM…" flow (#252) to drop an invite URL straight
/// into the recipient's thread composer.
///
/// Consumed on render: the thread body component drains this signal the
/// first time it matches its `(room, peer)` props, then clears it so a
/// second render doesn't reset what the user has subsequently typed.
pub static DM_DRAFT: GlobalSignal<Option<(VerifyingKey, MemberId, String)>> = Global::new(|| None);

/// In-memory cache of outbound DM plaintext, keyed by
/// `(room_owner_vk, recipient, purge_token)`. Hydrated from the chat
/// delegate on app startup and re-written on every send / purge. Used
/// by [`DmThreadModal`] (and CLI/`riverctl dm list` via the equivalent
/// CLI cache) to render the sender's own outbound bubbles as plaintext
/// instead of "sent — ciphertext only". See issue freenet/river#256.
///
/// Miss on lookup → caller falls back to the placeholder, so DMs sent
/// under older clients (pre-#256) continue to render as ciphertext-only.
pub static OUTBOUND_DMS: GlobalSignal<OutboundDmsCache> = Global::new(OutboundDmsCache::default);

/// In-memory shape of the outbound-DM cache. The on-disk form is
/// `river_core::chat_delegate::OutboundDmStore` (a `Vec` for JSON safety
/// per the bug-prevention pattern); we hold a `HashMap` here for O(1)
/// render-time lookup.
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct OutboundDmsCache {
    pub by_token: HashMap<(VerifyingKey, MemberId, PurgeToken), OutboundDmEntry>,
}

impl OutboundDmsCache {
    pub fn get(
        &self,
        room: &VerifyingKey,
        recipient: &MemberId,
        token: &PurgeToken,
    ) -> Option<&OutboundDmEntry> {
        self.by_token.get(&(*room, *recipient, *token))
    }

    /// Insert an entry — exposed so unit tests can construct a
    /// populated cache without depending on the delegate I/O path.
    /// Production callers should go through
    /// `chat_delegate::save_outbound_dm` to also get per-pair cap
    /// eviction and a delegate save.
    #[cfg(test)]
    pub(crate) fn insert_for_test(&mut self, entry: OutboundDmEntry) {
        let key = (
            ed25519_dalek::VerifyingKey::from_bytes(&entry.room_owner_vk)
                .expect("test entry has valid room VK"),
            entry.recipient,
            entry.purge_token,
        );
        self.by_token.insert(key, entry);
    }
}

/// Local view-state for issue freenet/river#261: per-`(room, peer)`
/// "hidden-at" cutoffs. A thread is hidden from
/// [`crate::components::room_list::dm_rail_section::DmRailSection`]
/// iff no message between the local user and `peer` in `room` is
/// strictly later than the recorded `hidden_at_ts`.
///
/// Persisted via the chat-delegate `OutboundDmStore.hidden_threads`
/// side-channel so a hide on device A propagates to device B (and
/// survives a reload on the same device). In-memory shape is a
/// `HashMap` keyed by `(room, peer)` for O(1) render-time lookup; the
/// on-disk shape is a `Vec` for JSON safety (see the "non-string map
/// keys" bug-prevention pattern).
pub static HIDDEN_DM_THREADS: GlobalSignal<HashMap<(VerifyingKey, MemberId), HiddenDmThreadEntry>> =
    Global::new(HashMap::new);

/// UI-side wrapper around `river_core::chat_delegate::is_thread_hidden`
/// that does the `VerifyingKey -> [u8; 32]` conversion at the boundary.
/// Kept as a thin shim so callers don't have to repeat the byte
/// conversion at every render site.
pub fn is_thread_hidden_for(
    hidden: &HashMap<(VerifyingKey, MemberId), HiddenDmThreadEntry>,
    room: &VerifyingKey,
    peer: MemberId,
    max_message_ts: u64,
) -> bool {
    hidden
        .get(&(*room, peer))
        .is_some_and(|h| max_message_ts <= h.hidden_at_ts)
}

/// Pure helper: decide how to render an outbound DM bubble given the
/// loaded plaintext cache.
///
/// `Ok(plaintext)` — render as user-supplied prose (markdown / linkify
/// pass). `Err(())` — render as the legacy `"sent — ciphertext only"`
/// placeholder (DM was sent before this cache shipped, or on a second
/// device whose cache hasn't hydrated yet, OR the cache entry is
/// missing for any other reason).
///
/// Pinned by `dm_outbound_lookup_returns_plaintext_on_hit` and
/// `dm_outbound_lookup_returns_err_on_miss` — issue freenet/river#256
/// regression coverage. Both `DmThreadModalBody` (UI) and the CLI
/// `execute_list` (via the same lookup tuple) MUST stay in agreement
/// with this helper.
pub fn lookup_outbound_plaintext(
    cache: &OutboundDmsCache,
    room: &VerifyingKey,
    recipient: &MemberId,
    token: &PurgeToken,
) -> Result<String, ()> {
    cache
        .get(room, recipient, token)
        .map(|entry| entry.plaintext.clone())
        .ok_or(())
}

/// Open the invite-via-DM picker for the given target peer in the current
/// room.
///
/// Refuses to open for `peer == self` even though all current callers gate
/// on that — defense in depth so a future shortcut doesn't strand a user
/// with a self-DM draft they can't send (Skeptical-review finding #3).
pub fn open_invite_via_dm_picker(current_room: VerifyingKey, peer: MemberId) {
    let Ok(rooms) = crate::components::app::ROOMS.try_read() else {
        return;
    };
    if let Some(room_data) = rooms.map.get(&current_room) {
        let self_id: MemberId = room_data.self_sk.verifying_key().into();
        if self_id == peer {
            dioxus::logger::tracing::warn!(
                "open_invite_via_dm_picker: refusing to open for self-as-peer"
            );
            return;
        }
    }
    drop(rooms);
    crate::util::defer(move || {
        *INVITE_VIA_DM_PICKER.write() = Some((current_room, peer));
    });
}

/// Tracks whether the one-shot DM-last-seen seed has already run for this
/// session. Once set, [`seed_dm_last_seen_if_needed`] is a no-op — which is
/// what we want: if it kept running on every `ROOMS` update, every newly-
/// arrived inbound DM would seed itself and never surface as unread (Codex
/// P2 on #244 review pass 3).
static DM_LAST_SEEN_SEEDED: GlobalSignal<bool> = Global::new(|| false);

/// Result of [`send_structured_dm`] — surfaced to the caller so the
/// picker / DM modal can either close + toast on success or render an
/// inline error string. Mirrors the `ApplyOutcome` shape used inside
/// `dm_thread_modal.rs`, but kept as its own enum here because the
/// surface is callable from outside the modal and we don't want the
/// modal-specific names leaking.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SendDmOutcome {
    /// Delta applied locally, `mark_needs_sync` queued, outbound cache
    /// updated. The caller should clear its composer / close its modal.
    Sent,
    /// The room we tried to send in is no longer in `ROOMS` (unloaded).
    RoomGone,
    /// The recipient is not currently a member of the room.
    RecipientNotMember,
    /// Sender == recipient.
    SelfDm,
    /// The local user has been pruned from the room's member list AND
    /// no rejoin credentials are available. The contract would silent-
    /// drop the DM. See `dm_thread_modal.rs`'s `SilentDrop` arm for the
    /// full diagnostic — same root cause.
    SenderMissingRejoin,
    /// The per-pair cap is at the limit; sending another DM would be
    /// silently dropped by the contract.
    CapHit,
    /// Body encoding failed (CBOR serialize error) or the resulting
    /// envelope exceeds `MAX_DM_CIPHERTEXT_BYTES`. Carries the error
    /// string from the underlying helper.
    BodyTooLargeOrEncodeFailed(String),
    /// `apply_delta` returned Err (signature / membership / tombstone /
    /// cap inside the contract layer). Deterministic — retrying byte-
    /// identical input gives the same result. Carries the diagnostic.
    DeltaFailed(String),
    /// `apply_delta` returned Ok but the message wasn't actually present
    /// in `direct_messages.messages` after the merge. Sender or
    /// recipient missing from members AND no rejoin bundle could fix
    /// it. See `ApplyOutcome::SilentDrop` in `dm_thread_modal.rs`.
    SilentDrop,
}

/// Compose, locally-apply, and queue for network sync a single direct
/// message with a structured `DirectMessageBody` (Text or Invite). This
/// is the canonical send-a-DM entry point for callers that need the
/// structured form — currently:
///
/// * [`crate::components::direct_messages::invite_via_dm_picker_modal`]
///   for the in-app "Share an invite via DM…" flow, which sends an
///   `Invite` variant directly (no `DM_DRAFT` URL paste).
///
/// `dm_thread_modal.rs::do_send` will move to this helper in a follow-
/// up commit — for now it still inlines the same logic for `Text`
/// bodies (verified equivalent by `send_structured_dm_text_matches_modal`
/// in the integration tests).
///
/// Returns an outcome the caller renders inline (no panicking, no
/// `expect`). Side effects on `Sent`: writes to `ROOMS`, calls
/// `mark_needs_sync`, calls `unhide_dm_thread`, persists outbound
/// plaintext into the delegate-backed cache.
///
/// **Plaintext stored in the outbound cache.** The cache key is
/// `(room, recipient, purge_token)`; the value is the user-facing
/// rendering of the body. For `Text { text }` that's just `text`; for
/// `Invite { personal_message, .. }` we store a JSON-encoded summary so
/// the sender's own list view doesn't lose the structured shape. The
/// recipient ignores this entirely — they decode the wire body itself.
pub async fn send_structured_dm(
    room: VerifyingKey,
    peer: MemberId,
    body: river_core::room_state::dm_body::DirectMessageBody,
) -> SendDmOutcome {
    use crate::components::app::chat_delegate::{save_outbound_dm, unhide_dm_thread};
    use crate::components::app::{mark_needs_sync, ROOMS};
    use freenet_scaffold::ComposableState;
    use river_core::room_state::direct_messages::{
        compose_direct_message, pair_message_count, DirectMessagesDelta, MAX_DM_MESSAGES_PER_PAIR,
    };
    use river_core::room_state::{ChatRoomParametersV1, ChatRoomStateV1Delta};

    // Snapshot what we need from ROOMS without holding the read guard
    // across the async work.
    let Some(room_data) = ROOMS
        .try_read()
        .ok()
        .and_then(|r| r.map.get(&room).cloned())
    else {
        return SendDmOutcome::RoomGone;
    };

    let self_sk = room_data.self_sk.clone();
    let self_id: MemberId = (&self_sk.verifying_key()).into();
    let owner_id = MemberId::from(&room);

    if self_id == peer {
        return SendDmOutcome::SelfDm;
    }

    // Resolve the peer's verifying key. Owner is implicit (not in members).
    let peer_vk = if peer == owner_id {
        room
    } else {
        match room_data
            .room_state
            .members
            .members
            .iter()
            .find(|m| m.member.id() == peer)
            .map(|m| m.member.member_vk)
        {
            Some(vk) => vk,
            None => return SendDmOutcome::RecipientNotMember,
        }
    };

    // Pre-flight per-pair cap. We re-check inside the defer write-lock
    // too, but surfacing it here gives a cleaner error path for the
    // picker (which can't easily re-try).
    let existing = pair_message_count(&room_data.room_state.direct_messages, self_id, peer);
    if existing >= MAX_DM_MESSAGES_PER_PAIR {
        return SendDmOutcome::CapHit;
    }

    // Rejoin bundle: matches `dm_thread_modal.rs::do_send`. Bug #1 (Ivvor,
    // 2026-05-16) — pruned-but-invited senders silently fail without this.
    let (rejoin_members, rejoin_member_info) = room_data.build_rejoin_delta();
    let self_in_members = self_id == owner_id
        || room_data
            .room_state
            .members
            .members
            .iter()
            .any(|m| m.member.id() == self_id);
    if !self_in_members && rejoin_members.is_none() {
        return SendDmOutcome::SenderMissingRejoin;
    }

    // Encode the body and capture the plaintext-summary BEFORE moving it.
    let body_bytes = match river_core::room_state::dm_body::encode_body(&body) {
        Ok(b) => b,
        Err(e) => return SendDmOutcome::BodyTooLargeOrEncodeFailed(e),
    };
    let plaintext_summary = summarise_body_for_outbound_cache(&body);

    let now = unix_now();
    let auth = match compose_direct_message(&self_sk, &peer_vk, &room, now, now, &body_bytes) {
        Ok(a) => a,
        Err(e) => return SendDmOutcome::BodyTooLargeOrEncodeFailed(e),
    };

    let purge_token = auth.purge_token();
    let dm_timestamp = auth.message.timestamp;
    let auth_sig = auth.sender_signature;

    let delta = ChatRoomStateV1Delta {
        members: rejoin_members,
        member_info: rejoin_member_info,
        direct_messages: Some(DirectMessagesDelta {
            new_messages: vec![auth],
            advanced_purges: vec![],
        }),
        ..Default::default()
    };
    let params = ChatRoomParametersV1 { owner: room };

    // Apply the delta under a write-lock on ROOMS. We `await` the
    // `apply_delta` result via a oneshot channel because Dioxus signal
    // writes must be deferred (AGENTS.md "Dioxus WASM Signal Safety
    // Rules"). The picker awaits us and reacts to the outcome.
    let (tx, rx) = futures::channel::oneshot::channel::<SendDmOutcome>();
    let plaintext_for_cache = plaintext_summary.clone();
    crate::util::defer(move || {
        let outcome = ROOMS.with_mut(|rooms| {
            let Some(rd) = rooms.map.get_mut(&room) else {
                return SendDmOutcome::RoomGone;
            };
            if pair_message_count(&rd.room_state.direct_messages, self_id, peer)
                >= MAX_DM_MESSAGES_PER_PAIR
            {
                return SendDmOutcome::CapHit;
            }
            let parent = rd.room_state.clone();
            if let Err(e) = rd.room_state.apply_delta(&parent, &params, &Some(delta)) {
                return SendDmOutcome::DeltaFailed(format!("{:?}", e));
            }
            // Verify the DM actually landed (defence-in-depth against
            // contract-side silent drop).
            let landed = rd
                .room_state
                .direct_messages
                .messages
                .iter()
                .any(|m| m.sender_signature == auth_sig);
            if !landed {
                return SendDmOutcome::SilentDrop;
            }
            SendDmOutcome::Sent
        });

        if matches!(outcome, SendDmOutcome::Sent) {
            mark_needs_sync(room);
            save_outbound_dm(
                room,
                self_id,
                peer,
                purge_token,
                dm_timestamp,
                plaintext_for_cache,
            );
            unhide_dm_thread(room, peer);
        }
        let _ = tx.send(outcome);
    });

    // Wait for the deferred work to land. Defer schedules via
    // setTimeout(0), so this is one macrotask away.
    rx.await.unwrap_or(SendDmOutcome::DeltaFailed(
        "deferred send aborted before completion".into(),
    ))
}

/// Compute the plaintext string we cache for the sender's own outbound
/// bubble rendering. For `Text` bodies that's just the text; for `Invite`
/// it's a human-readable summary so the sender's list view doesn't
/// render a blank "Invite (binary payload)" placeholder. The recipient
/// decodes the wire body directly — they never look at this string.
fn summarise_body_for_outbound_cache(
    body: &river_core::room_state::dm_body::DirectMessageBody,
) -> String {
    use river_core::room_state::dm_body::DirectMessageBody;
    match body {
        DirectMessageBody::Text { text } => text.clone(),
        DirectMessageBody::Invite {
            personal_message, ..
        } => match personal_message {
            Some(msg) if !msg.trim().is_empty() => {
                format!("[Invitation] {}", msg.trim())
            }
            _ => "[Invitation]".to_string(),
        },
    }
}

fn unix_now() -> u64 {
    use std::time::UNIX_EPOCH;
    crate::util::get_current_system_time()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Pure helper: compute the max inbound DM timestamp per `(room, peer)` in
/// `rooms`. Split from the signal-touching wrapper so it's unit-testable.
pub(crate) fn compute_dm_last_seen(
    rooms: &crate::room_data::Rooms,
) -> HashMap<(VerifyingKey, MemberId), u64> {
    let mut updates: HashMap<(VerifyingKey, MemberId), u64> = HashMap::new();
    for (owner_vk, room_data) in &rooms.map {
        let self_id: MemberId = room_data.self_sk.verifying_key().into();
        for msg in &room_data.room_state.direct_messages.messages {
            if msg.message.recipient != self_id {
                continue;
            }
            let key = (*owner_vk, msg.message.sender);
            let entry = updates.entry(key).or_insert(0);
            if msg.message.timestamp > *entry {
                *entry = msg.message.timestamp;
            }
        }
    }
    updates
}

/// Initialise [`DM_LAST_SEEN`] from current room state so previously-existing
/// inbound DMs don't show up as "unread" every time the page reloads.
///
/// `DM_LAST_SEEN` is in-memory only — that's an explicit limitation of the
/// first cut, documented in the module header. Without this seeding step,
/// every reload would mark every DM ever received as unread until the user
/// opened each thread, which is much noisier than the room-message badge
/// (which is durable via `last_read_message_id`).
///
/// **Subscription semantics.** The intended caller is a `use_effect` that
/// subscribes to [`crate::components::app::ROOMS`] so it fires the FIRST
/// time `ROOMS` hydrates from the delegate (it's empty on synchronous
/// app-component first render). The internal `DM_LAST_SEEN_SEEDED` flag
/// then makes every subsequent call a no-op: if we re-seeded on every
/// `ROOMS` update, a newly-arrived inbound DM would advance the cutoff to
/// its own timestamp and never appear as unread (Codex review #3 caught
/// this).
///
/// Per-`(room, peer)` last-seen is set to the maximum inbound timestamp
/// in that thread; anything newer than the current state still counts as
/// unread.
pub fn seed_dm_last_seen_if_needed() {
    // Cheap early-exit: if we've already seeded once, do nothing.
    if let Ok(g) = DM_LAST_SEEN_SEEDED.try_read() {
        if *g {
            return;
        }
    } else {
        return;
    };

    let Ok(rooms) = crate::components::app::ROOMS.try_read() else {
        return;
    };
    if rooms.map.is_empty() {
        // ROOMS hasn't hydrated yet; wait for the next ROOMS change.
        return;
    }
    let updates = compute_dm_last_seen(&rooms);
    drop(rooms);

    // Latch the seeded flag synchronously so any parallel re-run of this
    // effect (before the deferred write hits) immediately early-exits.
    // Doing the latch BEFORE the deferred write also avoids the
    // one-render-frame "every historical DM looks unread" window the
    // skeptical reviewer (#258 M3) flagged — consumers reading
    // DM_LAST_SEEN_SEEDED see "seeded, write in flight" rather than
    // "not seeded".
    //
    // Safety: a same-tick re-entry doesn't lose the seed because we
    // already computed `updates` from the just-read rooms snapshot and
    // captured it into the defer closure. The flag latch and the write
    // are conceptually one operation.
    crate::util::defer(move || {
        *DM_LAST_SEEN_SEEDED.write() = true;
        DM_LAST_SEEN.with_mut(|seen| {
            for (key, ts) in updates {
                let entry = seen.entry(key).or_insert(0);
                if ts > *entry {
                    *entry = ts;
                }
            }
        });
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::room_data::{RoomData, Rooms};
    use ed25519_dalek::{SigningKey, VerifyingKey};
    use freenet_stdlib::prelude::{ContractCode, ContractKey, Parameters};
    use river_core::room_state::configuration::{AuthorizedConfigurationV1, Configuration};
    use river_core::room_state::direct_messages::sign_direct_message;
    use river_core::room_state::member::{AuthorizedMember, Member, MembersV1};
    use river_core::ChatRoomStateV1;

    fn empty_rooms() -> Rooms {
        Rooms {
            map: std::collections::HashMap::new(),
            current_room_key: None,
            migrated_rooms: Vec::new(),
            removed_rooms: std::collections::HashSet::new(),
        }
    }

    fn fixed_sk(seed: u8) -> SigningKey {
        SigningKey::from_bytes(&[seed; 32])
    }

    /// Build a `Rooms` with one room owned by `owner_sk`, with
    /// `self_sk` as the local user enrolled as a member.
    fn make_rooms(owner_sk: &SigningKey, self_sk: &SigningKey, other_sks: &[&SigningKey]) -> Rooms {
        let owner_vk = owner_sk.verifying_key();
        let owner_id: MemberId = (&owner_vk).into();
        let mut members: Vec<AuthorizedMember> = vec![AuthorizedMember::new(
            Member {
                owner_member_id: owner_id,
                invited_by: owner_id,
                member_vk: self_sk.verifying_key(),
            },
            owner_sk,
        )];
        for s in other_sks {
            members.push(AuthorizedMember::new(
                Member {
                    owner_member_id: owner_id,
                    invited_by: owner_id,
                    member_vk: s.verifying_key(),
                },
                owner_sk,
            ));
        }
        let auth_config = AuthorizedConfigurationV1::new(Configuration::default(), owner_sk);
        let state = ChatRoomStateV1 {
            configuration: auth_config,
            members: MembersV1 { members },
            ..Default::default()
        };
        let mut rooms = empty_rooms();
        let contract_code = ContractCode::from(crate::constants::ROOM_CONTRACT_WASM);
        let contract_key = ContractKey::from_params_and_code(
            Parameters::from(crate::util::to_cbor_vec(
                &river_core::room_state::ChatRoomParametersV1 { owner: owner_vk },
            )),
            &contract_code,
        );
        rooms.map.insert(
            owner_vk,
            RoomData {
                owner_vk,
                room_state: state,
                self_sk: self_sk.clone(),
                contract_key,
                last_read_message_id: None,
                secrets: std::collections::HashMap::new(),
                current_secret_version: None,
                last_secret_rotation: None,
                key_migrated_to_delegate: false,
                self_authorized_member: None,
                invite_chain: Vec::new(),
                self_member_info: None,
                previous_contract_key: None,
            },
        );
        rooms
    }

    fn push_dm(
        rooms: &mut Rooms,
        room_owner_vk: &VerifyingKey,
        sender_sk: &SigningKey,
        recipient_vk: &VerifyingKey,
        ts: u64,
    ) {
        let auth = sign_direct_message(
            sender_sk,
            (&sender_sk.verifying_key()).into(),
            recipient_vk.into(),
            room_owner_vk,
            ts,
            b"opaque".to_vec(),
        )
        .expect("sign_direct_message");
        rooms
            .map
            .get_mut(room_owner_vk)
            .unwrap()
            .room_state
            .direct_messages
            .messages
            .push(auth);
    }

    #[test]
    fn compute_dm_last_seen_returns_empty_for_empty_rooms() {
        let updates = compute_dm_last_seen(&empty_rooms());
        assert!(updates.is_empty());
    }

    #[test]
    fn compute_dm_last_seen_only_counts_inbound_to_self() {
        let owner = fixed_sk(1);
        let me = fixed_sk(2);
        let alice = fixed_sk(3);
        let bob = fixed_sk(4);
        let owner_vk = owner.verifying_key();
        let mut rooms = make_rooms(&owner, &me, &[&alice, &bob]);

        // Alice -> me at ts 100; Bob -> me at ts 200; me -> Alice at ts 250
        // (outbound; must NOT contribute).
        push_dm(&mut rooms, &owner_vk, &alice, &me.verifying_key(), 100);
        push_dm(&mut rooms, &owner_vk, &bob, &me.verifying_key(), 200);
        push_dm(&mut rooms, &owner_vk, &me, &alice.verifying_key(), 250);

        let updates = compute_dm_last_seen(&rooms);
        let alice_id: MemberId = (&alice.verifying_key()).into();
        let bob_id: MemberId = (&bob.verifying_key()).into();
        assert_eq!(updates.get(&(owner_vk, alice_id)), Some(&100));
        assert_eq!(updates.get(&(owner_vk, bob_id)), Some(&200));
        // Outbound DM: must NOT seed against my own self_id.
        let me_id: MemberId = (&me.verifying_key()).into();
        assert!(updates.get(&(owner_vk, me_id)).is_none());
    }

    #[test]
    fn compute_dm_last_seen_takes_max_per_peer() {
        let owner = fixed_sk(11);
        let me = fixed_sk(12);
        let alice = fixed_sk(13);
        let owner_vk = owner.verifying_key();
        let mut rooms = make_rooms(&owner, &me, &[&alice]);

        // Three DMs from Alice; the helper must pick the max.
        push_dm(&mut rooms, &owner_vk, &alice, &me.verifying_key(), 100);
        push_dm(&mut rooms, &owner_vk, &alice, &me.verifying_key(), 1_000);
        push_dm(&mut rooms, &owner_vk, &alice, &me.verifying_key(), 500);

        let updates = compute_dm_last_seen(&rooms);
        let alice_id: MemberId = (&alice.verifying_key()).into();
        assert_eq!(updates.get(&(owner_vk, alice_id)), Some(&1_000));
    }

    fn sample_outbound_entry(
        room_vk: VerifyingKey,
        recipient: MemberId,
        token: PurgeToken,
        plaintext: &str,
    ) -> OutboundDmEntry {
        OutboundDmEntry {
            room_owner_vk: room_vk.to_bytes(),
            sender: MemberId::from(&fixed_sk(99).verifying_key()),
            recipient,
            purge_token: token,
            timestamp: 1_700_000_000,
            plaintext: plaintext.to_string(),
        }
    }

    /// Issue freenet/river#256 regression: a cache hit on
    /// `(room, recipient, purge_token)` MUST return the original
    /// plaintext so the sender's own outbound bubble renders as
    /// markdown prose instead of the "sent — ciphertext only"
    /// placeholder. Pins the load-bearing lookup tuple — any future
    /// refactor that drops a field from the key (or swaps key order)
    /// fails this test.
    #[test]
    fn dm_outbound_lookup_returns_plaintext_on_hit() {
        let room_vk = fixed_sk(1).verifying_key();
        let recipient: MemberId = (&fixed_sk(2).verifying_key()).into();
        let token = PurgeToken([0x42; 16]);

        let mut cache = OutboundDmsCache::default();
        cache.insert_for_test(sample_outbound_entry(room_vk, recipient, token, "hello!"));

        let resolved = lookup_outbound_plaintext(&cache, &room_vk, &recipient, &token);
        assert_eq!(resolved, Ok("hello!".to_string()));
    }

    /// Issue freenet/river#256 regression: a cache miss MUST surface
    /// as `Err(())` so the caller falls back to the legacy
    /// `"sent — ciphertext only"` placeholder. Three miss-scenarios
    /// pin all three components of the lookup tuple are load-bearing.
    #[test]
    fn dm_outbound_lookup_returns_err_on_miss() {
        let room_vk = fixed_sk(1).verifying_key();
        let other_room_vk = fixed_sk(7).verifying_key();
        let recipient: MemberId = (&fixed_sk(2).verifying_key()).into();
        let other_recipient: MemberId = (&fixed_sk(3).verifying_key()).into();
        let token = PurgeToken([0x42; 16]);
        let other_token = PurgeToken([0xff; 16]);

        let mut cache = OutboundDmsCache::default();
        cache.insert_for_test(sample_outbound_entry(room_vk, recipient, token, "hello!"));

        // Wrong room.
        assert_eq!(
            lookup_outbound_plaintext(&cache, &other_room_vk, &recipient, &token),
            Err(())
        );
        // Wrong recipient.
        assert_eq!(
            lookup_outbound_plaintext(&cache, &room_vk, &other_recipient, &token),
            Err(())
        );
        // Wrong token.
        assert_eq!(
            lookup_outbound_plaintext(&cache, &room_vk, &recipient, &other_token),
            Err(())
        );
        // Empty cache.
        let empty = OutboundDmsCache::default();
        assert_eq!(
            lookup_outbound_plaintext(&empty, &room_vk, &recipient, &token),
            Err(())
        );
    }
}
