[package]
name = "freenet-scaffold-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
# Proc macro dependencies
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
