[application]

# App (Project) Name
name = "chatui"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "web"

# `build` & `serve` dist path
out_dir = "dist"

# resource (assets) file folder
asset_dir = "assets"

[web.app]

# Todo - this won't work for local serving, need to fix
base_path = "v1/contract/web/HFZunbY1EA8mvZMrUzW5Urt2noZSnMW3z8jYsPpCocvf"

# HTML title tag content
title = "River"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# CSS style file
#style = ["bulma.min.css", "main.css", "fontawesome/css/all.min.css"]

# Javascript code file
script = []

# Static files to be included in the project
include = ["fontawesome/webfonts"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


