name: Build

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: freenet-default-runner

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Cache cargo-make
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-make
    
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --force cargo-make

    - name: Install cargo-binstall
      uses: taiki-e/install-action@cargo-binstall

    - name: Install Dioxus CLI
      run: cargo binstall -y dioxus-cli
    
    - name: Prefetch dependencies
      run: |
        cargo fetch --locked || {
          echo "Locked prefetch failed; falling back to non-locked fetch (lockfile likely outdated).";
          cargo fetch;
        }
      
    - name: Build Project
      run: cargo make build

  claude-ci-analysis:
    name: Claude CI Analysis

    runs-on: ubuntu-latest
    needs: [build]
    if: failure() && contains(github.event.pull_request.labels.*.name, 'claude-debug')

    permissions:
      contents: read
      pull-requests: write
      issues: read
      id-token: write
      actions: read

    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude CI Analysis
        uses: anthropics/claude-code-action@v1
        with:
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            The CI workflow has failed. Please analyze the failure and provide:
            1. Root cause of the failure
            2. Specific steps to fix the issue
            3. Whether this appears to be a flaky test or genuine bug
            4. Any relevant context from the codebase

            Use the repository's CLAUDE.md for guidance on testing and debugging.

            After your analysis, use `gh pr comment` with your Bash tool to post your findings as a comment on the PR.

          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr view:*),Bash(gh pr list:*),Bash(gh api:*),Bash(gh run view:*)"'
