name: Dioxus Build

on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: freenet-core-ci

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install Dioxus CLI
      run: cargo install dioxus-cli
      
    - name: Build Dioxus Project
      run: |
        cd ui
        dx build
