name: Dioxus Build

on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: freenet-core-ci

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Build Room Contract
      run: |
        cd contracts/room-contract
        cargo build --release --target wasm32-unknown-unknown -p room-contract
    - name: Cache Dioxus CLI
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/dx
        key: ${{ runner.os }}-dioxus-cli
    
    - name: Install Dioxus CLI
      run: cargo install dioxus-cli
      
    - name: Build Dioxus Project
      run: |
        cd ui
        dx build
