name: Dioxus Build

on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: freenet-default-runner

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Verify submodule
      run: |
        ls -la stdlib/
        ls -la stdlib/rust/
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --force cargo-make
      
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - name: Cache Dioxus CLI
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/dx
        key: ${{ runner.os }}-dioxus-cli
    
    - name: Install Dioxus CLI
      run: cargo install dioxus-cli --force
      
    - name: Build Project
      run: cargo make build
