name: Test

on:
  push:
    branches: [ "**" ]  # Run on all branches
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: freenet-default-runner

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target/
        key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-test-
    
    - name: Cache cargo-make
      uses: actions/cache@v3
      with:
        path: ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-make
    
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --force cargo-make
      
    - name: Run Tests
      run: cargo make test
