[package]
name = "chat-delegate"
version = "0.1.0"
edition = "2021"

[features]
default = ["freenet-main-delegate"]
freenet-main-delegate = []

[dependencies]
ciborium.workspace = true
freenet-stdlib.workspace = true
bs58 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
river-core.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

